const books = {
  "Isaiah": {
    "Chapter 1": {
      "header": "0. Israel’s ancient apostasy typifies an end-time apostasy, with salvation reserved for some who repent.",
      "verses": [
        "1. The vision of Isaiah the son of Amoz which he beheld concerning Judea and Jerusalem during the reigns of Uzziah, Jotham, Ahaz, and Hezekiah, kings of Judah:",
        "2. Hear, O heavens! Give heed, O earth!\nJehovah has spoken:\nI have reared sons, brought them up,\nbut they have revolted against me.",
        "3. The ox knows its owner,\nthe ass its master’s stall,\nbut Israel does not know;\nmy people are insensible.",
        "4. Alas, a nation astray,\na people weighed down by sin,\nthe offspring of wrongdoers,\nperverse children:\nthey have forsaken Jehovah,\nthey have spurned the Holy One of Israel,\nthey have lapsed into apostasy.",
        "5. Why be smitten further\nby adding to your waywardness?\nThe whole head is sick,\nthe whole heart diseased.",
        "6. From the soles of the feet even to the head\nthere is nothing sound,\nonly wounds and bruises and festering sores;\nthey have not been pressed out or bound up,\nnor soothed with ointment.",
        "7. Your land is ruined,\nyour cities burned with fire;\nyour native soil is devoured by aliens in your presence,\nlaid waste at its takeover by foreigners.",
        "8. The Daughter of Zion is left\nlike a shelter in a vineyard,\na hut in a melon field,\na city under siege.",
        "9. Had not Jehovah of Hosts left us a few survivors,\nwe should have been as Sodom,\nor become like Gomorrah.",
        "10. Hear the word of Jehovah,\nO leaders of Sodom;\ngive heed to the law of our God,\nyou people of Gomorrah!",
        "11. For what purpose are your abundant\nsacrifices to me? says Jehovah.\nI have had my fill of offerings of rams\nand fat of fatted beasts;\nthe blood of bulls and sheep and he-goats\nI do not want.",
        "12. When you come to see me,\nwho requires you to trample my courts so?",
        "13. Bring no more worthless offerings;\nthey are as a loathsome incense to me.\nAs for convening meetings at the New Month\nand on the Sabbath,\nwickedness with the solemn gathering\nI cannot approve.",
        "14. Your monthly and regular meetings\nmy soul detests.\nThey have become a burden on me;\nI am weary of putting up with them.",
        "15. When you spread forth your hands,\nI will conceal my eyes from you;\nthough you pray at length, I will not hear—\nyour hands are filled with blood.",
        "16. Wash yourselves clean:\nremove your wicked deeds\nfrom before my eyes;\ncease to do evil.",
        "17. Learn to do good: demand justice,\nstand up for the oppressed;\nplead the cause of the fatherless,\nappeal on behalf of the widow.",
        "18. Come now, let us put it to the test,\nsays Jehovah:\nthough your sins are as scarlet,\nthey can be made white as snow;\nthough they have reddened as crimson,\nthey may become white as wool.",
        "19. If you are willing and obey,\nyou shall eat the good of the land.",
        "20. But if you are unwilling and disobey,\nyou shall be eaten by the sword.\nBy his mouth Jehovah has spoken it.",
        "21. How the faithful city\nhas become a harlot!\nShe was filled with justice;\nrighteousness made its abode in her,\nbut now murderers.",
        "22. Your silver has become dross,\nyour wine diluted with water.",
        "23. Your rulers are renegades,\naccomplices of robbers:\nwith one accord they love bribes\nand run after rewards;\nthey do not dispense justice to the fatherless,\nnor does the widow’s case come before them.",
        "24. Therefore the Lord, Jehovah of Hosts,\nthe Valiant One of Israel, declares,\nWoe to them! I will relieve me\nof my adversaries,\navenge me of my enemies.",
        "25. I will restore my hand over you\nand smelt away your dross as in a crucible,\nand remove all your alloy.",
        "26. I will restore your judges as at the first,\nand your counsellors as in the beginning.\nAfter this you shall be called\nthe City of Righteousness, a faithful city.",
        "27. For Zion shall be ransomed by justice,\nthose of her who repent by righteousness.",
        "28. But criminals and sinners\nshall be altogether shattered\nwhen those who forsake Jehovah are annihilated.",
        "29. And you will be ashamed of the oaks you cherished\nand blush for the parks you were fond of;",
        "30. you shall become like an oak whose leaves wither,\nand as a garden that has no water.",
        "31. The mighty shall be as refuse,\nand their works a spark;\nboth shall burn up alike,\nand there shall be none to extinguish."
      ]
    },
    "Chapter 2": {
      "header": "0. The end-time restoration of Zion/Jerusalem contrasts Jehovah’s judgment of the world at his coming.",
      "verses": [
        "1. A prophecy concerning Judea and Jerusalem which Isaiah the son of Amoz saw in vision:",
        "2. In the latter days\nthe mountain of Jehovah’s house\nshall become established\nas the head of the mountains;\nit shall be preeminent among the hills,\nand all nations will flow to it.",
        "3. Many peoples shall go, saying,\nCome, let us go up\nto the mountain of Jehovah,\nto the house of the God of Jacob,\nthat he may instruct us in his ways,\nthat we may follow in his paths.\nFor out of Zion shall go forth the law,\nand from Jerusalem the word of Jehovah.",
        "4. He will judge between the nations\nand arbitrate for many peoples.\nThey will beat their swords into plowshares,\ntheir spears into pruning hooks:\nnation will not lift the sword against nation,\nnor will they learn warfare any more.",
        "5. O house of Jacob, come,\nlet us follow the light of Jehovah.",
        "6. For you, O Jehovah, have forsaken your people,\nthe house of Jacob, because,\nlike the Philistines,\nthey provide themselves with\nmystics from the East\nand are content with the infantile heathen.",
        "7. Their land is full of silver and gold\nand there is no end to their wealth;\ntheir land is full of horses\nand there is no end to their chariots.",
        "8. Their land is full of idols:\nthey adore the works of their hands,\nthings their own fingers have made.",
        "9. Mankind is brought low\nwhen men thus debase themselves.\nForbear them not!",
        "10. Go into the rocks; hide in the dust\nfrom the awesome presence of Jehovah\nand from the brightness of his glory.",
        "11. The haughty eyes of men shall be lowered\nand man’s pride abased;\nJehovah alone shall be exalted in that day.",
        "12. Jehovah of Hosts has a day in store\nfor all the proud and arrogant\nand for all who are exalted,\nthat they may be brought low.",
        "13. It shall come against all the lofty\ncedars of Lebanon that lift themselves up high,\nand against all the oaks of Bashan,",
        "14. against all high mountains and elevated hills,",
        "15. against every tall tower and reinforced wall,",
        "16. against [all vessels at sea,]\nboth merchant ships and pleasure craft.",
        "17. The haughtiness of men shall be abased,\nand man’s pride brought low;\nJehovah alone shall be exalted in that day.",
        "18. He will utterly supplant the false gods.",
        "19. Men will go into caves in the rocks\nand holes in the ground,\nfrom the awesome presence of Jehovah\nand from the brightness of his glory,\nwhen he arises and strikes terror on earth.",
        "20. In that day men will throw away\nto the moles and to the bats\ntheir idols of silver and gods of gold\nwhich they have made for themselves\nto adore.",
        "21. Men will go into crevices in the rocks\nand fissures in the cliffs,\nfrom the awesome presence of Jehovah\nand from the brightness of his glory,\nwhen he arises and strikes terror on earth.",
        "22. Desist from the things of man,\nin whose nostrils is but breath!\nFor of what consideration is he?"
      ]
    },
    "Chapter 3": {
      "header": "0. Wickedness in society leads to anarchy, internal collapse, destitution, and invasion by enemies.",
      "verses": [
        "1. Even now, the Lord, Jehovah of Hosts,\ndeprives Judea and Jerusalem\nof both staff and crutch—\nall food supply and water supply,",
        "2. the valiant man and soldier,\nthe magistrate and prophet, the augur and elder,",
        "3. the officer and dignitary,\nadvisers, skilled craftsmen, and orators.",
        "4. I, Jehovah, will make adolescents their rulers;\ndelinquents will lord it over them.",
        "5. People will oppress one another,\nevery man his neighbor.\nThe young will be insolent to the elderly,\nthe vile to the honorable.",
        "6. Then will a man apprehend a kinsman\nof his father’s house, and say,\nYou have a tunic: be our leader\nand take charge of this ruination!",
        "7. But he will raise his hand in that day\nand swear, I am no physician.\nThere is neither food nor clothing in my house;\nyou cannot make me a leader of the people.",
        "8. Jerusalem will falter and Judea fall\nbecause their tongue and their actions\nare contrary to Jehovah,\nan affront to his glory before his very eyes.",
        "9. The look on their faces betrays them:\nthey flaunt their sin like Sodom;\nthey cannot hide it.\nWoe to their souls;\nthey have brought disaster upon themselves!",
        "10. Tell the righteous it shall be well with them;\nthey shall eat the fruits of their own labors.",
        "11. But woe to the wicked\nwhen calamity overtakes them:\nthey shall be paid back\nfor the deeds they have done!",
        "12. As for my people, babes subject them;\nwomen wield authority over them.\nO my people, your leaders mislead you,\nabolishing your traditional ways.",
        "13. Jehovah will take a stand and contend with them;\nhe has arisen to judge the nations.",
        "14. He will bring to trial the elders of his people\nand their rulers, and say to them,\nIt is you who have devoured the vineyard;\nyou fill your houses by depriving the needy.",
        "15. What do you mean by oppressing my people,\nhumbling the faces of the poor?\nsays Jehovah of Hosts.",
        "16. Jehovah says, moreover,\nBecause the women of Zion are haughty\nand put on airs, painting their eyes,\never flirting when they walk\nand clacking with their feet,",
        "17. my Lord will afflict the scalps\nof the women of Zion with baldness;\nJehovah will expose their private parts.",
        "18. In that day my Lord will strip away their finery—the anklets, head ornaments and crescents,",
        "19. the pendants, chains and scarves,",
        "20. tiaras, bracelets and ribbons, zodiac signs and charm amulets,",
        "21. the rings, the noselets,",
        "22. the elegant dress, the shawl, the kerchief and the purse,",
        "23. hosiery, sheer linen, millinery, and cloaks.",
        "24. And instead of perfume there shall be a stench,\ninstead of the girdle, a piece of twine,\ninstead of the coiffure, baldness,\ninstead of the festive dress, a loincloth of burlap;\nfor in place of beauty\nthere shall be ignominy.",
        "25. Your men shall be felled by the sword,\nyour might overthrown in war.",
        "26. Her gateways shall lie bereaved and forlorn;\nshe shall sit on the ground destitute."
      ]
    },
    "Chapter 4": {
      "header": "0. In his Day of Judgment Jehovah preserves alive those whose names are inscribed in the Book of Life.",
      "verses": [
        "1. Seven women will take hold of one man\nin that day, and say,\nWe will eat our own food,\nwear our own clothes,\nonly let us be called by your name—\ntake away our reproach!",
        "2. In that day the plant of Jehovah shall be beautiful and glorious, and the earth’s fruit the pride and glory of the survivors of Israel.",
        "3. Then shall they who are left in Zion and they who remain in Jerusalem be called holy—all who were inscribed to be among the living at Jerusalem.",
        "4. This shall be when my Lord has washed away the excrement of the women of Zion and cleansed Jerusalem of its bloodshed, in the spirit of justice, by a burning wind.",
        "5. Over the whole site of Mount Zion, and over its solemn assembly, Jehovah will form a cloud by day and a mist glowing with fire by night: above all that is glorious shall be a canopy.",
        "6. It shall be a shelter and shade from the heat of the day, a secret refuge from the downpour and from rain."
      ]
    },
    "Chapter 5": {
      "header": "0. Jehovah’s vineyard yields bad fruit, leading to Assyria’s invasion and covenant curses on offenders.",
      "verses": [
        "1. Let me sing for my Beloved\na love song about his vineyard:\nMy Beloved had a vineyard\non the fertile brow of a hill.",
        "2. He cultivated it, clearing it of stones,\nand planted it with choice vines.\nHe built a watchtower in its midst\nand hewed for it a winepress as well.\nThen he expected it to yield grapes,\nbut it produced wild grapes.",
        "3. Now, O inhabitants of Jerusalem and you men of Judea,\nplease judge between me and my vineyard!",
        "4. What more could have been done\nfor my vineyard than I have done for it?\nWhen I expected it to yield grapes,\nwhy did it produce wild grapes?",
        "5. Let me now inform you\nwhat I will do to my vineyard:\nI will have its hedge removed\nand let it be burned;\nI will have its wall broken through\nand let it be trampled.",
        "6. I will make it a desolation:\nit shall neither be pruned nor hoed,\nbut briars and thorns shall overgrow it.\nMoreover, I will forbid the rainclouds to rain on it.",
        "7. The vineyard of Jehovah of Hosts is the house of Israel\nand the people of Judah his cherished grove.\nHe expected justice,\nbut there was injustice;\nhe expected righteousness,\nbut there was an outcry.",
        "8. Woe to those who join house to house\nand link field to field till no place is left,\nand you are restricted to dwell\nin the centers of the land!",
        "9. Jehovah of Hosts spoke this in my hearing:\nSurely many buildings shall lie desolate,\nlarge and fine houses unoccupied.",
        "10. A ten-acre vineyard shall yield but one bath,\na homer of seed but an ephah.",
        "11. Woe to those who go after liquor\nas soon as they arise in the morning,\nwho linger at night parties, inflamed by wine!",
        "12. There are harps and lyres,\ndrums, flutes, and wine at their banquets,\nbut they regard not what Jehovah does,\nnor perceive his hands at work.",
        "13. Therefore are my people exiled\nwithout knowing why;\ntheir best men die of famine,\ntheir masses perish with thirst.",
        "14. Sheol becomes ravenous,\nopening its mouth insatiably;\ninto it descend their elite with the masses,\ntheir boisterous ones and revelers.",
        "15. Mankind is brought low\nwhen men debase themselves,\ncausing the eyes of the high-minded to be downcast.",
        "16. But Jehovah of Hosts will be exalted\nby a just judgment,\nthe holy God show himself holy\nby his righteousness.",
        "17. Then shall his sheep feed in their pasture,\nand proselytes eat in the ruins of the affluent.",
        "18. Woe to those drawn to sin by vain attachments,\nhitched to transgression like a trailer,",
        "19. who think, Let him quickly speed up his work\nso we may see it!\nLet the plan of the Holy One of Israel\nsoon come to pass, and we will know!",
        "20. Woe to those who suppose what is evil to be good\nand what is good, evil!\nThey put darkness for light\nand light for darkness;\nthey make bitterness sweet and the sweet bitter.",
        "21. Woe to those who are wise in their own eyes\nand clever in their own view!",
        "22. Woe to those who are valiant at drinking wine\nand champions at mixing liquor!",
        "23. Woe to those who acquit the guilty for a bribe\nbut deny justice to the innocent!",
        "24. As a blazing fire consumes stubble,\nand as dry weeds wane before the flame,\nso shall their roots decay away\nand their blossoms fly up like dust.\nFor they have despised the law of Jehovah of Hosts\nand reviled the words of the Holy One of Israel.",
        "25. Therefore the anger of Jehovah is kindled\nagainst his people:\nhe draws back his hand against them\nand strikes them;\nthe mountains quake, and their corpses\nlie like litter about the streets.\nYet for all this his anger is not abated;\nhis hand is upraised still.",
        "26. He raises an ensign to distant nations\nand summons them from beyond the horizon.\nForthwith they come, swiftly and speedily.",
        "27. Not one of them grows weary,\nnor does any stumble;\nthey do not drowse or fall asleep.\nTheir waist-belts come not loose\nnor their sandal thongs undone.",
        "28. Their arrows are sharp;\nall their bows are strung.\nThe tread of their warhorses resembles flint;\ntheir chariot wheels revolve like a whirlwind.",
        "29. They have the roar of a lion;\nthey are aroused like young lions:\ngrowling, they seize the prey, and escape,\nand none comes to the rescue.",
        "30. He shall be stirred up against them in that day,\neven as the Sea is stirred up.\nAnd should one look to the land,\nthere too shall be a distressing gloom,\nfor the daylight shall be darkened\nby an overhanging mist."
      ]
    },
    "Chapter 6": {
      "header": "0. Jehovah appears to Isaiah in the temple and sends him as a prophet to warn of imminent judgments.",
      "verses": [
        "1. In the year of King Uzziah’s death, I saw my Lord seated on a throne, highly exalted, the skirt of his robe filling the sanctuary.",
        "2. Seraphs stood by him overhead, each having six wings— with two they could veil their presence, with two conceal their location, and with two fly about.",
        "3. They called out to one another, and said,\nMost holy is Jehovah of Hosts;\nthe consummation of all the earth is his glory!",
        "4. The threshold shook to its foundation at the sound of those who called and a mist filled the temple.",
        "5. Then I thought, Woe is me: I have been struck dumb, for I am a man of unclean speech, and I live among a people of unclean speech: I have seen the King, Jehovah of Hosts, with my own eyes!",
        "6. Then one of the seraphs flew to me carrying an ember which he had taken with tongs from the altar.",
        "7. Touching it to my mouth, he said, See, this has touched your lips: your sins are taken away, your transgressions atoned for.",
        "8. Then I heard the voice of my Lord saying, Whom shall I send? Who will go for us? And I replied, Here am I; send me!",
        "9. And he said, Go, and say to these people,\nGo on hearing, but not understanding;\nGo on seeing, but not perceiving.",
        "10. Make the heart of these people grow fat;\ndull their ears and shut their eyes,\nlest they see with their eyes\nand hear with their ears,\nunderstand in their heart,\nand repent, and be healed.",
        "11. And I replied, For how long, my Lord? And he said,\nUntil the cities lie desolate\nand without inhabitant,\nthe houses without a man,\nand the land ravaged to ruin.",
        "12. For Jehovah will drive men away,\nand great shall be the exodus\nfrom the centers of the land.",
        "13. And while yet a tenth of the people\nremain in it, or return,\nthey shall be burned.\nBut like the terebinth or the oak\nwhen it is felled, whose stump remains alive,\nso shall the holy offspring be what is left standing."
      ]
    },
    "Chapter 7": {
      "header": "0. King Ahaz’ transgression of the terms of his covenant leads to a hostile world power gaining supremacy.",
      "verses": [
        "1. When Ahaz son of Jotham, the son of Uzziah, was king of Judah, Rezin king of Aram and Pekah son of Remaliah king of Israel came up to Jerusalem to wage war against it, but could not overpower it.",
        "2. And when the house of David was informed that Aram was leading Ephraim on, the king’s mind and the minds of his people were shaken, as trees in a forest are shaken by a gale.",
        "3. Then Jehovah said to Isaiah, Go out and meet Ahaz, you and your son Shear-Jashub, at the end of the aqueduct of the Upper Reservoir, on the road to the Laundry Plaza.",
        "4. Say to him, See to it that you remain calm and unafraid. Be not intimidated by these two smoking tail ends of kindling, by the burning anger of Rezin and Aram and the son of Remaliah,",
        "5. even though Aram has conceived an evil plot against you, as has Ephraim and the son of Remaliah, who say,",
        "6. Let us invade Judah and stir up trouble there. We will take it for ourselves by force and set a ruler over it—the son of Tabeal.",
        "7. Thus says my Lord Jehovah:\nIt shall not occur or transpire.",
        "8. For as surely as Damascus is the capital of Aram\nand Rezin the head of Damascus,\nwithin sixty-five years shall Ephraim\nbe shattered as a nation.",
        "9. But as surely as Samaria is the capital of Ephraim\nand the son of Remaliah the head of Samaria,\nyou will not believe it,\nbecause you are not loyal.",
        "10. Again Jehovah addressed Ahaz, and said,",
        "11. Ask a sign for yourself from Jehovah your God, whether in the depths below or in the heights above.",
        "12. But Ahaz said, I will not. I will not put Jehovah to the test.",
        "13. Then Isaiah said, Take heed, O house of David! Is it not enough for you to try the patience of men? Must you also try the patience of my God?",
        "14. Therefore will my Lord of himself give you a sign: the young woman with child shall give birth to a son and name him Immanuel.",
        "15. Cream and honey will he eat by the time he has learned to reject what is evil and choose what is good.",
        "16. But before the child learns to reject the evil and choose the good, the land whose two rulers you loathe shall lie forsaken.",
        "17. Jehovah will bring upon you and your people and your father’s house a day unlike any since Ephraim broke away from Judah—the day of the king of Assyria.",
        "18. In that day Jehovah will signal for the flies from the far rivers of Egypt and for the bees in the land of Assyria.",
        "19. And they will come and settle with one accord in the river beds of the prairie and in rocky ravines, and by all ditches and water holes.",
        "20. In that day my Lord will use a razor hired at the River—the king of Assyria—to shave your head and the hair of your legs, and to cut off even your beard.",
        "21. In that day a man will keep alive a young cow and a pair of sheep.",
        "22. And because of their plentiful milk, men will eat the cream. All who remain in the land will feed on cream and honey.",
        "23. In that day every plot of ground with a thousand vines worth a thousand pieces of currency shall be briars and thorns.",
        "24. Men will go there with bows and arrows, for the whole land shall revert to wilderness.",
        "25. And on all hillsides cultivated by the hoe you will no longer go for fear of the briars and thorns, but they shall serve as a cattle range, a terrain for sheep to tread down."
      ]
    }
  }
};